judge if exists summary-report.htm first
if summary-report.htm doesn't exist, executing /usr/bin/wkhtmltopdf
command will result in this error.
Error: Failed loading page
http:///polydata/sandbox/storage/analyses/8039/reports/summary-report.html
(sometimes it will work just to ignore this error with
--ignore-load-errors)